class PartsDB:
    cpu = {
        1: {
            "name": "AMD Ryzen 5 5600X",
            "core_count": 6,
            "perfomance_core_clock": "3.7 GHz",
            "perfomance_boost_clock": "4.6 GHz",
            "TDP": "65 W",
            "integrated_graphics": "None",
            "SMT": "yes",
            "price": "$162.66",
        },
        2: {
            "name": "AMD Ryzen 7 5800X",
            "core_count": 8,
            "perfomance_core_clock": "3.8 GHz",
            "perfomance_boost_clock": "4.7 GHz",
            "TDP": "105 W",
            "integrated_graphics": "None",
            "SMT": "yes",
            "price": "$217.99",
        },
        3: {
            "name": "Intel Core i7-13700K",
            "core_count": 16,
            "perfomance_core_clock": "3.4 GHz",
            "perfomance_boost_clock": "5.4 GHz",
            "TDP": "125 W",
            "integrated_graphics": "Intel UHD Graphics 770",
            "SMT": "yes",
            "price": "$409.00",
        },
    }
    storage = {
        1: {
            "name": "Samsung 980 Pro",
            "capacity": "2 TB",
            "type": "SSD",
            "cache": "2048 MB",
            "form_factor": "M.2-2280",
            "interface": "M.2 PCle 4.0 X4",
            "price": "$119.99",
        },
        2: {
            "name": "Samsung 970 Evo Plius",
            "capacity": "1 TB",
            "type": "SSD",
            "cache": "1024 MB",
            "form_factor": "M.2-2280",
            "interface": "M.2 PCle 3.0 X4",
            "price": "$49.99",
        },
        3: {
            "name": "Samsung 980 Pro",
            "capacity": "1 TB",
            "type": "SSD",
            "cache": "1024 MB",
            "form_factor": "M.2-2280",
            "interface": "M.2 PCle 4.0 X4",
            "price": "$69.99",
        },
    }
